# Source: aws-load-balancer-controller
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRZmIzeldPNDNpTU51SStqTmtLUnRlVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF3TXpFd05UQXlOMW9YRFRNMk1ETXpNVEV3TlRBeU4xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXBGQVdOYWtwN0ZveEloYWJvY0VISGRsUkNtZGZ1WWcxQ2NodFFVeG1RdG12ZTYzM1pLbU5PNgpWRG5held6UUtWTjN5Qm9sK0ZGaGZFNGJUc3ZVaTg2bFROTW5KWERCK2VUMzhyNExIZmt3N0U5aEpPS3gxbGc5CkpYMDloenRrMzg1Z2tBMVllRFJOblAxMzB0eVRCQjRzcFczVkhBN0JuUXd0eVh0bThwTkNmRXRjQzlpRW0vVk8Kb0gxa1VuV3RGZzZ2cXhqQ1hEeVdYQmNrUy80dGphSEFVemd6Q2loWktVTCsyS08rWkQzMi9OTk03eVZVZE83VQpFdFdDRFhTQXJrSFJsd0dwemJ2K0djZkRZaG1zNy9Ob004dlQzRS9oQW50ZVdOUVRWbWR1TXJZcWNRak1nZjYrCmhCYzBvUlViSHFvcy9LdWRMRklCanJWdE82OVZsWXNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFlTURUYk1ManVZZ1VrWnhDWmpkUmhYV3ZoZERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFnaXRseSt2aTJibWdMOEpuL2E1TVFRYkhoR0J0S1RLZ3ZVRFF2OEdTQW9RSnVSdmJWd0xCdGhWRmtRemwKZjFjaW5nTGptWExSNTA4QmxRa2J4enVjRFRJUW1EZEFNZFB5ZDFBMld1VUlpT3R4anFIMkpJSVlmRzBkTURJUQpXMEh3djg2YnFXTTd3b0w1dlJoNERwbEx4d0s5cWYxUWszZDZ2SGVicEMzekRLS280WU51TEptZGhDYVVzNzJhCjloc0pPN2FuZzZWNHdIdFlJY2NNOU9rTms1UXZINy9YT2llek5HZU1TNU1SRXRkVXEzYWszTzRvaTU0OC9JNVkKU3Uxd3pHZ0xxcUo5dXpkY29Xd2RHd3FDODNtWG1BbGwxRi9LOEdIMUM0ZHo4TXJSOFNBZzY3cXRldFNDMzlkbwpWd1RyeHI2K09CeG43S0Y3NERqb2FuS2NCdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-v1-pod
  failurePolicy: Ignore
  name: mpod.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  namespaceSelector:
    matchExpressions:
    - key: elbv2.k8s.aws/pod-readiness-gate-inject
      operator: In
      values:
      - enabled
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRZmIzeldPNDNpTU51SStqTmtLUnRlVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF3TXpFd05UQXlOMW9YRFRNMk1ETXpNVEV3TlRBeU4xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXBGQVdOYWtwN0ZveEloYWJvY0VISGRsUkNtZGZ1WWcxQ2NodFFVeG1RdG12ZTYzM1pLbU5PNgpWRG5held6UUtWTjN5Qm9sK0ZGaGZFNGJUc3ZVaTg2bFROTW5KWERCK2VUMzhyNExIZmt3N0U5aEpPS3gxbGc5CkpYMDloenRrMzg1Z2tBMVllRFJOblAxMzB0eVRCQjRzcFczVkhBN0JuUXd0eVh0bThwTkNmRXRjQzlpRW0vVk8Kb0gxa1VuV3RGZzZ2cXhqQ1hEeVdYQmNrUy80dGphSEFVemd6Q2loWktVTCsyS08rWkQzMi9OTk03eVZVZE83VQpFdFdDRFhTQXJrSFJsd0dwemJ2K0djZkRZaG1zNy9Ob004dlQzRS9oQW50ZVdOUVRWbWR1TXJZcWNRak1nZjYrCmhCYzBvUlViSHFvcy9LdWRMRklCanJWdE82OVZsWXNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFlTURUYk1ManVZZ1VrWnhDWmpkUmhYV3ZoZERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFnaXRseSt2aTJibWdMOEpuL2E1TVFRYkhoR0J0S1RLZ3ZVRFF2OEdTQW9RSnVSdmJWd0xCdGhWRmtRemwKZjFjaW5nTGptWExSNTA4QmxRa2J4enVjRFRJUW1EZEFNZFB5ZDFBMld1VUlpT3R4anFIMkpJSVlmRzBkTURJUQpXMEh3djg2YnFXTTd3b0w1dlJoNERwbEx4d0s5cWYxUWszZDZ2SGVicEMzekRLS280WU51TEptZGhDYVVzNzJhCjloc0pPN2FuZzZWNHdIdFlJY2NNOU9rTms1UXZINy9YT2llek5HZU1TNU1SRXRkVXEzYWszTzRvaTU0OC9JNVkKU3Uxd3pHZ0xxcUo5dXpkY29Xd2RHd3FDODNtWG1BbGwxRi9LOEdIMUM0ZHo4TXJSOFNBZzY3cXRldFNDMzlkbwpWd1RyeHI2K09CeG43S0Y3NERqb2FuS2NCdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-v1-pod-server-id
  failurePolicy: Fail
  name: quicid.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  namespaceSelector:
    matchExpressions:
    - key: elbv2.k8s.aws/quic-server-id-inject
      operator: In
      values:
      - enabled
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRZmIzeldPNDNpTU51SStqTmtLUnRlVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF3TXpFd05UQXlOMW9YRFRNMk1ETXpNVEV3TlRBeU4xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXBGQVdOYWtwN0ZveEloYWJvY0VISGRsUkNtZGZ1WWcxQ2NodFFVeG1RdG12ZTYzM1pLbU5PNgpWRG5held6UUtWTjN5Qm9sK0ZGaGZFNGJUc3ZVaTg2bFROTW5KWERCK2VUMzhyNExIZmt3N0U5aEpPS3gxbGc5CkpYMDloenRrMzg1Z2tBMVllRFJOblAxMzB0eVRCQjRzcFczVkhBN0JuUXd0eVh0bThwTkNmRXRjQzlpRW0vVk8Kb0gxa1VuV3RGZzZ2cXhqQ1hEeVdYQmNrUy80dGphSEFVemd6Q2loWktVTCsyS08rWkQzMi9OTk03eVZVZE83VQpFdFdDRFhTQXJrSFJsd0dwemJ2K0djZkRZaG1zNy9Ob004dlQzRS9oQW50ZVdOUVRWbWR1TXJZcWNRak1nZjYrCmhCYzBvUlViSHFvcy9LdWRMRklCanJWdE82OVZsWXNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFlTURUYk1ManVZZ1VrWnhDWmpkUmhYV3ZoZERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFnaXRseSt2aTJibWdMOEpuL2E1TVFRYkhoR0J0S1RLZ3ZVRFF2OEdTQW9RSnVSdmJWd0xCdGhWRmtRemwKZjFjaW5nTGptWExSNTA4QmxRa2J4enVjRFRJUW1EZEFNZFB5ZDFBMld1VUlpT3R4anFIMkpJSVlmRzBkTURJUQpXMEh3djg2YnFXTTd3b0w1dlJoNERwbEx4d0s5cWYxUWszZDZ2SGVicEMzekRLS280WU51TEptZGhDYVVzNzJhCjloc0pPN2FuZzZWNHdIdFlJY2NNOU9rTms1UXZINy9YT2llek5HZU1TNU1SRXRkVXEzYWszTzRvaTU0OC9JNVkKU3Uxd3pHZ0xxcUo5dXpkY29Xd2RHd3FDODNtWG1BbGwxRi9LOEdIMUM0ZHo4TXJSOFNBZzY3cXRldFNDMzlkbwpWd1RyeHI2K09CeG43S0Y3NERqb2FuS2NCdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-v1-service
  failurePolicy: Fail
  name: mservice.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - services
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRZmIzeldPNDNpTU51SStqTmtLUnRlVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF3TXpFd05UQXlOMW9YRFRNMk1ETXpNVEV3TlRBeU4xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXBGQVdOYWtwN0ZveEloYWJvY0VISGRsUkNtZGZ1WWcxQ2NodFFVeG1RdG12ZTYzM1pLbU5PNgpWRG5held6UUtWTjN5Qm9sK0ZGaGZFNGJUc3ZVaTg2bFROTW5KWERCK2VUMzhyNExIZmt3N0U5aEpPS3gxbGc5CkpYMDloenRrMzg1Z2tBMVllRFJOblAxMzB0eVRCQjRzcFczVkhBN0JuUXd0eVh0bThwTkNmRXRjQzlpRW0vVk8Kb0gxa1VuV3RGZzZ2cXhqQ1hEeVdYQmNrUy80dGphSEFVemd6Q2loWktVTCsyS08rWkQzMi9OTk03eVZVZE83VQpFdFdDRFhTQXJrSFJsd0dwemJ2K0djZkRZaG1zNy9Ob004dlQzRS9oQW50ZVdOUVRWbWR1TXJZcWNRak1nZjYrCmhCYzBvUlViSHFvcy9LdWRMRklCanJWdE82OVZsWXNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFlTURUYk1ManVZZ1VrWnhDWmpkUmhYV3ZoZERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFnaXRseSt2aTJibWdMOEpuL2E1TVFRYkhoR0J0S1RLZ3ZVRFF2OEdTQW9RSnVSdmJWd0xCdGhWRmtRemwKZjFjaW5nTGptWExSNTA4QmxRa2J4enVjRFRJUW1EZEFNZFB5ZDFBMld1VUlpT3R4anFIMkpJSVlmRzBkTURJUQpXMEh3djg2YnFXTTd3b0w1dlJoNERwbEx4d0s5cWYxUWszZDZ2SGVicEMzekRLS280WU51TEptZGhDYVVzNzJhCjloc0pPN2FuZzZWNHdIdFlJY2NNOU9rTms1UXZINy9YT2llek5HZU1TNU1SRXRkVXEzYWszTzRvaTU0OC9JNVkKU3Uxd3pHZ0xxcUo5dXpkY29Xd2RHd3FDODNtWG1BbGwxRi9LOEdIMUM0ZHo4TXJSOFNBZzY3cXRldFNDMzlkbwpWd1RyeHI2K09CeG43S0Y3NERqb2FuS2NCdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-alb-target-control-namespace-v1-pod
  failurePolicy: Fail
  name: alb-target-control.namespace.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  namespaceSelector:
    matchExpressions:
    - key: elbv2.k8s.aws/alb-target-control-agent-injection
      operator: In
      values:
      - enabled
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
    - key: elbv2.k8s.aws/alb-target-control-agent-inject
      operator: NotIn
      values:
      - 'false'
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRZmIzeldPNDNpTU51SStqTmtLUnRlVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF3TXpFd05UQXlOMW9YRFRNMk1ETXpNVEV3TlRBeU4xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXBGQVdOYWtwN0ZveEloYWJvY0VISGRsUkNtZGZ1WWcxQ2NodFFVeG1RdG12ZTYzM1pLbU5PNgpWRG5held6UUtWTjN5Qm9sK0ZGaGZFNGJUc3ZVaTg2bFROTW5KWERCK2VUMzhyNExIZmt3N0U5aEpPS3gxbGc5CkpYMDloenRrMzg1Z2tBMVllRFJOblAxMzB0eVRCQjRzcFczVkhBN0JuUXd0eVh0bThwTkNmRXRjQzlpRW0vVk8Kb0gxa1VuV3RGZzZ2cXhqQ1hEeVdYQmNrUy80dGphSEFVemd6Q2loWktVTCsyS08rWkQzMi9OTk03eVZVZE83VQpFdFdDRFhTQXJrSFJsd0dwemJ2K0djZkRZaG1zNy9Ob004dlQzRS9oQW50ZVdOUVRWbWR1TXJZcWNRak1nZjYrCmhCYzBvUlViSHFvcy9LdWRMRklCanJWdE82OVZsWXNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFlTURUYk1ManVZZ1VrWnhDWmpkUmhYV3ZoZERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFnaXRseSt2aTJibWdMOEpuL2E1TVFRYkhoR0J0S1RLZ3ZVRFF2OEdTQW9RSnVSdmJWd0xCdGhWRmtRemwKZjFjaW5nTGptWExSNTA4QmxRa2J4enVjRFRJUW1EZEFNZFB5ZDFBMld1VUlpT3R4anFIMkpJSVlmRzBkTURJUQpXMEh3djg2YnFXTTd3b0w1dlJoNERwbEx4d0s5cWYxUWszZDZ2SGVicEMzekRLS280WU51TEptZGhDYVVzNzJhCjloc0pPN2FuZzZWNHdIdFlJY2NNOU9rTms1UXZINy9YT2llek5HZU1TNU1SRXRkVXEzYWszTzRvaTU0OC9JNVkKU3Uxd3pHZ0xxcUo5dXpkY29Xd2RHd3FDODNtWG1BbGwxRi9LOEdIMUM0ZHo4TXJSOFNBZzY3cXRldFNDMzlkbwpWd1RyeHI2K09CeG43S0Y3NERqb2FuS2NCdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-alb-target-control-object-v1-pod
  failurePolicy: Fail
  name: alb-target-control.object.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  namespaceSelector:
    matchExpressions:
    - key: elbv2.k8s.aws/alb-target-control-agent-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
    - key: elbv2.k8s.aws/alb-target-control-agent-inject
      operator: In
      values:
      - 'true'
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRZmIzeldPNDNpTU51SStqTmtLUnRlVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF3TXpFd05UQXlOMW9YRFRNMk1ETXpNVEV3TlRBeU4xb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTXBGQVdOYWtwN0ZveEloYWJvY0VISGRsUkNtZGZ1WWcxQ2NodFFVeG1RdG12ZTYzM1pLbU5PNgpWRG5held6UUtWTjN5Qm9sK0ZGaGZFNGJUc3ZVaTg2bFROTW5KWERCK2VUMzhyNExIZmt3N0U5aEpPS3gxbGc5CkpYMDloenRrMzg1Z2tBMVllRFJOblAxMzB0eVRCQjRzcFczVkhBN0JuUXd0eVh0bThwTkNmRXRjQzlpRW0vVk8Kb0gxa1VuV3RGZzZ2cXhqQ1hEeVdYQmNrUy80dGphSEFVemd6Q2loWktVTCsyS08rWkQzMi9OTk03eVZVZE83VQpFdFdDRFhTQXJrSFJsd0dwemJ2K0djZkRZaG1zNy9Ob004dlQzRS9oQW50ZVdOUVRWbWR1TXJZcWNRak1nZjYrCmhCYzBvUlViSHFvcy9LdWRMRklCanJWdE82OVZsWXNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFlTURUYk1ManVZZ1VrWnhDWmpkUmhYV3ZoZERBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFnaXRseSt2aTJibWdMOEpuL2E1TVFRYkhoR0J0S1RLZ3ZVRFF2OEdTQW9RSnVSdmJWd0xCdGhWRmtRemwKZjFjaW5nTGptWExSNTA4QmxRa2J4enVjRFRJUW1EZEFNZFB5ZDFBMld1VUlpT3R4anFIMkpJSVlmRzBkTURJUQpXMEh3djg2YnFXTTd3b0w1dlJoNERwbEx4d0s5cWYxUWszZDZ2SGVicEMzekRLS280WU51TEptZGhDYVVzNzJhCjloc0pPN2FuZzZWNHdIdFlJY2NNOU9rTms1UXZINy9YT2llek5HZU1TNU1SRXRkVXEzYWszTzRvaTU0OC9JNVkKU3Uxd3pHZ0xxcUo5dXpkY29Xd2RHd3FDODNtWG1BbGwxRi9LOEdIMUM0ZHo4TXJSOFNBZzY3cXRldFNDMzlkbwpWd1RyeHI2K09CeG43S0Y3NERqb2FuS2NCdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: mtargetgroupbinding.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
