# Source: aws-load-balancer-controller
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU8xTXBPUUJQbUpHM0R0YVFLMjlWM2N3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakEwTURJeU1ERXlNalZhRncwek5qQXpNekF5TURFeU1qVmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURMTmxGTVA2TXByUGFzOXFiOHJ2eW45RlY1Sk93ME5zMjg3VTRSRzd2Q01ScVRsOHpGRjZFOAo4LzhzaGdsZk9kelYwa3EzYWxxa08yRFFiZVF0dEY3bjNORm05QUw0VkJaOFRhM2lobllaK2lubDJncnhNV0wrCmY5bDEzRVhNTEZMWmhRR1p6UTJ0ME5sRHA4aXVrM05FbGRGYWFhdCs2eUowcVI4YVR2cmhUK2tSNXI0WEdUOVQKYjNlSkhtNVE2enlVcU4vZGxFRFRlSW9pYm9rK3RwcC9ydWE2TG5JTHRlM2hwdW8vaXdQdlo0UDJ6MU51cDdZcAp1d2tDT0xLVVBFUEF1R1NhbHBubFdVWm1za0duRmlkS0psWUVlU3ZPOXFNNzRVY2ZYWnFCVS92bkVFSWdFTTg5CmhCMVorSERpaDYvNEozd09jVk5WM0wvQkZxTld5clJqQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVK0VpTXRzUFp3QzNjOUt3b2ZPZlh4LzdudUlVd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSFhwNXk4bFFxbmlGbEVLcmZVNEFFRGhZUlBEa3U1SEhmZy95RmNCVENqOWFPOUx0Q0dyUnpCTUNldUMKaHM2RTBvdU9iN1hHYk50aDZsTXRzcEw2K3hNZmp3Q05PZnlLNWV4aklhSlUvbWxBMGp4dEk0UUcxMzByK1BpTwpkY2xVSm5UYXMwNFBCd3MrU2VYcTB4R1lLSzVJU0VWRFFlc24vT1VPTWZIWXJ3VEQvRENyZ2dJN21CbW5MTTBoCmJkZGF5Rlc1OGh3NndVaWtLdi91MENRZWU3NncybWdTMUMrNVJFNHVOWXdZLytQb2szZStMSmJuYVdEZ3N3Y3QKRzdVZ2FLNU1MMHpFM0RjM2tQc1NXblhEbkxTUWpwbCtiS0NKVnhsOEtZYVJjUElUWTJ3NmE1L096dG1ZK0QyagoxWE9kTUY5WTZXdk12KzRxdGF3ZkMrOU4ySms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
  failurePolicy: Fail
  name: vingressclassparams.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingressclassparams
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU8xTXBPUUJQbUpHM0R0YVFLMjlWM2N3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakEwTURJeU1ERXlNalZhRncwek5qQXpNekF5TURFeU1qVmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURMTmxGTVA2TXByUGFzOXFiOHJ2eW45RlY1Sk93ME5zMjg3VTRSRzd2Q01ScVRsOHpGRjZFOAo4LzhzaGdsZk9kelYwa3EzYWxxa08yRFFiZVF0dEY3bjNORm05QUw0VkJaOFRhM2lobllaK2lubDJncnhNV0wrCmY5bDEzRVhNTEZMWmhRR1p6UTJ0ME5sRHA4aXVrM05FbGRGYWFhdCs2eUowcVI4YVR2cmhUK2tSNXI0WEdUOVQKYjNlSkhtNVE2enlVcU4vZGxFRFRlSW9pYm9rK3RwcC9ydWE2TG5JTHRlM2hwdW8vaXdQdlo0UDJ6MU51cDdZcAp1d2tDT0xLVVBFUEF1R1NhbHBubFdVWm1za0duRmlkS0psWUVlU3ZPOXFNNzRVY2ZYWnFCVS92bkVFSWdFTTg5CmhCMVorSERpaDYvNEozd09jVk5WM0wvQkZxTld5clJqQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVK0VpTXRzUFp3QzNjOUt3b2ZPZlh4LzdudUlVd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSFhwNXk4bFFxbmlGbEVLcmZVNEFFRGhZUlBEa3U1SEhmZy95RmNCVENqOWFPOUx0Q0dyUnpCTUNldUMKaHM2RTBvdU9iN1hHYk50aDZsTXRzcEw2K3hNZmp3Q05PZnlLNWV4aklhSlUvbWxBMGp4dEk0UUcxMzByK1BpTwpkY2xVSm5UYXMwNFBCd3MrU2VYcTB4R1lLSzVJU0VWRFFlc24vT1VPTWZIWXJ3VEQvRENyZ2dJN21CbW5MTTBoCmJkZGF5Rlc1OGh3NndVaWtLdi91MENRZWU3NncybWdTMUMrNVJFNHVOWXdZLytQb2szZStMSmJuYVdEZ3N3Y3QKRzdVZ2FLNU1MMHpFM0RjM2tQc1NXblhEbkxTUWpwbCtiS0NKVnhsOEtZYVJjUElUWTJ3NmE1L096dG1ZK0QyagoxWE9kTUY5WTZXdk12KzRxdGF3ZkMrOU4ySms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: vtargetgroupbinding.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQU8xTXBPUUJQbUpHM0R0YVFLMjlWM2N3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakEwTURJeU1ERXlNalZhRncwek5qQXpNekF5TURFeU1qVmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURMTmxGTVA2TXByUGFzOXFiOHJ2eW45RlY1Sk93ME5zMjg3VTRSRzd2Q01ScVRsOHpGRjZFOAo4LzhzaGdsZk9kelYwa3EzYWxxa08yRFFiZVF0dEY3bjNORm05QUw0VkJaOFRhM2lobllaK2lubDJncnhNV0wrCmY5bDEzRVhNTEZMWmhRR1p6UTJ0ME5sRHA4aXVrM05FbGRGYWFhdCs2eUowcVI4YVR2cmhUK2tSNXI0WEdUOVQKYjNlSkhtNVE2enlVcU4vZGxFRFRlSW9pYm9rK3RwcC9ydWE2TG5JTHRlM2hwdW8vaXdQdlo0UDJ6MU51cDdZcAp1d2tDT0xLVVBFUEF1R1NhbHBubFdVWm1za0duRmlkS0psWUVlU3ZPOXFNNzRVY2ZYWnFCVS92bkVFSWdFTTg5CmhCMVorSERpaDYvNEozd09jVk5WM0wvQkZxTld5clJqQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVK0VpTXRzUFp3QzNjOUt3b2ZPZlh4LzdudUlVd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSFhwNXk4bFFxbmlGbEVLcmZVNEFFRGhZUlBEa3U1SEhmZy95RmNCVENqOWFPOUx0Q0dyUnpCTUNldUMKaHM2RTBvdU9iN1hHYk50aDZsTXRzcEw2K3hNZmp3Q05PZnlLNWV4aklhSlUvbWxBMGp4dEk0UUcxMzByK1BpTwpkY2xVSm5UYXMwNFBCd3MrU2VYcTB4R1lLSzVJU0VWRFFlc24vT1VPTWZIWXJ3VEQvRENyZ2dJN21CbW5MTTBoCmJkZGF5Rlc1OGh3NndVaWtLdi91MENRZWU3NncybWdTMUMrNVJFNHVOWXdZLytQb2szZStMSmJuYVdEZ3N3Y3QKRzdVZ2FLNU1MMHpFM0RjM2tQc1NXblhEbkxTUWpwbCtiS0NKVnhsOEtZYVJjUElUWTJ3NmE1L096dG1ZK0QyagoxWE9kTUY5WTZXdk12KzRxdGF3ZkMrOU4ySms9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-networking-v1-ingress
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vingress.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
