# Source: aws-load-balancer-controller
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-load-balancer-webhook
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUw1Mm9vaFg0eUZnSEdrQnVHbGV1Yzh3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakEwTURJeE9ESXhNemxhRncwek5qQXpNekF4T0RJeE16bGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNtWHRiVm8yTnBPa05mU1plNUxzeWFuOEtpa3p2Sm50VzRDTU9PNjM5OTQwaDVvd0Rra204RQpjQkxDYWVWdzdKSG1pckw3V09IYzV3MnlwcHgvMnZvazRoSTFzWmI1VUJTOTJiQ1dPbzZjSzY0ZTMyVTZmME9MCnQ2OGM4ZWFMWmZKZzRzcUlDMElZUXd0QVk1YVVMekthaEwxREF5V015SGFzZjZvOU5vVTE1d3Z3UmJySEovLzUKYlVSNnNTUjNyNFhDY24wRkszdnpSVUhlMXRKTFRBWGsxclR0aTJSNWUvVFlUbE80eFhrTFpoR0pqODVWMGRQZApLYXBjVjdLcFZYZkRjOGtVUStFVm5ickZzSkora0M0clduWG5NeFU2TmJmeHRPZWR6UitTaEd0TDhqV3dvRCtYCjNPajhLckJDYmlZZTMrb211RnBlYzhVV3ExWnNrZUJ0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVWnVXd1Q2UjlOTEtoMHBnazBDVENCN1RnR2Rnd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBQUdFdnRoeDhIRUU3ckdDeWtoYjh2aXhJdmt4by9iU2xsWE9LNGh6d1FDanR6cDNyb1k0ZUlLK0xjR3QKdktvRDRmYk5CVG1hTzhQcmNRek14MHNWNEs4NFAxcVBiaGM5ZStoOGpnOFZSdU5OUGJNVWZOWGFGV0Zjd3g3awpveW44bTRSTXFHdXJRdFhKUWdSQmk0WTFxTW1BU2pqQjQrc1BJK0hwb2R2Q05rTnU0a3ZTbEhoVFA2UTArbTZQCjZWSlVoUVdvMVJQUGVKVUpHcHdjM1JNUWJtVlRsUVV3OFVKOXFSNXZZTlVYbkM4dmk1SVFKU3djY3NqVjlFcXQKWGIyWkpnT3Bnb05QQlBjZm1XRmZ1Z1BwQUNzYXJkV3h3akNObzdIRHU5VGRDNloxeFNpdjQ4eXJWdlNQbFlFRwpqQ3lrMmhCSU1TUkpZYWVxa1VDeE5CRWNWVE09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
  failurePolicy: Fail
  name: vingressclassparams.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - aws-load-balancer-controller
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingressclassparams
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUw1Mm9vaFg0eUZnSEdrQnVHbGV1Yzh3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakEwTURJeE9ESXhNemxhRncwek5qQXpNekF4T0RJeE16bGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNtWHRiVm8yTnBPa05mU1plNUxzeWFuOEtpa3p2Sm50VzRDTU9PNjM5OTQwaDVvd0Rra204RQpjQkxDYWVWdzdKSG1pckw3V09IYzV3MnlwcHgvMnZvazRoSTFzWmI1VUJTOTJiQ1dPbzZjSzY0ZTMyVTZmME9MCnQ2OGM4ZWFMWmZKZzRzcUlDMElZUXd0QVk1YVVMekthaEwxREF5V015SGFzZjZvOU5vVTE1d3Z3UmJySEovLzUKYlVSNnNTUjNyNFhDY24wRkszdnpSVUhlMXRKTFRBWGsxclR0aTJSNWUvVFlUbE80eFhrTFpoR0pqODVWMGRQZApLYXBjVjdLcFZYZkRjOGtVUStFVm5ickZzSkora0M0clduWG5NeFU2TmJmeHRPZWR6UitTaEd0TDhqV3dvRCtYCjNPajhLckJDYmlZZTMrb211RnBlYzhVV3ExWnNrZUJ0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVWnVXd1Q2UjlOTEtoMHBnazBDVENCN1RnR2Rnd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBQUdFdnRoeDhIRUU3ckdDeWtoYjh2aXhJdmt4by9iU2xsWE9LNGh6d1FDanR6cDNyb1k0ZUlLK0xjR3QKdktvRDRmYk5CVG1hTzhQcmNRek14MHNWNEs4NFAxcVBiaGM5ZStoOGpnOFZSdU5OUGJNVWZOWGFGV0Zjd3g3awpveW44bTRSTXFHdXJRdFhKUWdSQmk0WTFxTW1BU2pqQjQrc1BJK0hwb2R2Q05rTnU0a3ZTbEhoVFA2UTArbTZQCjZWSlVoUVdvMVJQUGVKVUpHcHdjM1JNUWJtVlRsUVV3OFVKOXFSNXZZTlVYbkM4dmk1SVFKU3djY3NqVjlFcXQKWGIyWkpnT3Bnb05QQlBjZm1XRmZ1Z1BwQUNzYXJkV3h3akNObzdIRHU5VGRDNloxeFNpdjQ4eXJWdlNQbFlFRwpqQ3lrMmhCSU1TUkpZYWVxa1VDeE5CRWNWVE09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
  failurePolicy: Fail
  name: vtargetgroupbinding.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - elbv2.k8s.aws
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - targetgroupbindings
  sideEffects: None
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUw1Mm9vaFg0eUZnSEdrQnVHbGV1Yzh3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakEwTURJeE9ESXhNemxhRncwek5qQXpNekF4T0RJeE16bGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNtWHRiVm8yTnBPa05mU1plNUxzeWFuOEtpa3p2Sm50VzRDTU9PNjM5OTQwaDVvd0Rra204RQpjQkxDYWVWdzdKSG1pckw3V09IYzV3MnlwcHgvMnZvazRoSTFzWmI1VUJTOTJiQ1dPbzZjSzY0ZTMyVTZmME9MCnQ2OGM4ZWFMWmZKZzRzcUlDMElZUXd0QVk1YVVMekthaEwxREF5V015SGFzZjZvOU5vVTE1d3Z3UmJySEovLzUKYlVSNnNTUjNyNFhDY24wRkszdnpSVUhlMXRKTFRBWGsxclR0aTJSNWUvVFlUbE80eFhrTFpoR0pqODVWMGRQZApLYXBjVjdLcFZYZkRjOGtVUStFVm5ickZzSkora0M0clduWG5NeFU2TmJmeHRPZWR6UitTaEd0TDhqV3dvRCtYCjNPajhLckJDYmlZZTMrb211RnBlYzhVV3ExWnNrZUJ0QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVWnVXd1Q2UjlOTEtoMHBnazBDVENCN1RnR2Rnd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBQUdFdnRoeDhIRUU3ckdDeWtoYjh2aXhJdmt4by9iU2xsWE9LNGh6d1FDanR6cDNyb1k0ZUlLK0xjR3QKdktvRDRmYk5CVG1hTzhQcmNRek14MHNWNEs4NFAxcVBiaGM5ZStoOGpnOFZSdU5OUGJNVWZOWGFGV0Zjd3g3awpveW44bTRSTXFHdXJRdFhKUWdSQmk0WTFxTW1BU2pqQjQrc1BJK0hwb2R2Q05rTnU0a3ZTbEhoVFA2UTArbTZQCjZWSlVoUVdvMVJQUGVKVUpHcHdjM1JNUWJtVlRsUVV3OFVKOXFSNXZZTlVYbkM4dmk1SVFKU3djY3NqVjlFcXQKWGIyWkpnT3Bnb05QQlBjZm1XRmZ1Z1BwQUNzYXJkV3h3akNObzdIRHU5VGRDNloxeFNpdjQ4eXJWdlNQbFlFRwpqQ3lrMmhCSU1TUkpZYWVxa1VDeE5CRWNWVE09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: aws-load-balancer-webhook-service
      namespace: kube-system
      path: /validate-networking-v1-ingress
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vingress.elbv2.k8s.aws
  admissionReviewVersions:
  - v1beta1
  rules:
  - apiGroups:
    - networking.k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  sideEffects: None
